### ISSUE TITLE
Doesn't support iPhone 5

### ISSUE THREAD

**Issue by shinrenpan** [heitorfr/ios-image-editor#1]
HFImageEditorFrameView doesn't autoresizing
![1](https://f.cloud.github.com/assets/1157368/63650/4f6f96ba-5df9-11e2-86c6-93f3d37aaa5c.jpg)

**Comment by shinrenpan** [comment]
Fixed issue follow
1. setting imageView autoresizingMask in HFImageEditorFrameView or Interface builder
2.call method [self updateCropRect] and [self reset:NO] in HFImageEditorViewController viewWillAppear or sub class

**Comment by heitorfr** [comment]
Thanks, I'll get at it asap. The frame view was initially part of the demo, so I didn't get all the attention it needed :)

**Comment by heitorfr** [comment]
Done. You're analysis was spot on
