### ISSUE TITLE
image jump out of screen after scale

### ISSUE THREAD

**Issue by shuhankuang** [heitorfr/ios-image-editor#11]
if i scale the image with a very small size, then the image will jump out of the crop box, and may be jump out of screen.

**Comment by heitorfr** [comment]
Are you using checkBounds=YES? And in that case did you disable rotation (rotateEnabled =NO)?

**Comment by kvting** [comment]
I had the same problem that @shuhankuang and I did use checkBounds and disable rotation.
The problem is in `- (BOOL)handleGestureState:(UIGestureRecognizerState)state` when you do the `if(self.checkBounds) [self doCheckBounds];`
I'll send you a pull request to solve this issue.

**Comment by heitorfr** [comment]
I've updated the check bounds implementation, now supports rotation too, yeay

**Comment by kvting** [comment]
Great!
