### ISSUE TITLE
HFImageEditorViewController can't handle paronams

### ISSUE THREAD

**Issue by ksteel** [heitorfr/ios-image-editor#14]
If someone attempts to select and save a Panaroma image being feed it to HFImageEditViewController memory warnings are thrown and the device resets. Upon running on an iPhone 5 with Instruments, when a user attempts to crop and save (doneAction:) memory allocations spike to over 1.5 gb.

**Comment by heitorfr** [comment]
What is the image size in pixels?

**Comment by heitorfr** [comment]
Image processing is now more efficient (from 1.1.1). If you have any problems, reopen with more detail
