### ISSUE TITLE
how to use with storyboard ?

### ISSUE THREAD

**Issue by kohdesmond** [heitorfr/ios-image-editor#19]
Hi Heitorfr,

i have issues using your editor with storyboard.
i'm getting uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSArrayM insertObject:atIndex:]: object cannot be nil' error.

how do i initialise it ?

cheers

des

**Comment by amre3l** [comment]
Solved the problem by adding this

```
_panRecognizer = [[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(handlePan:)];
_rotationRecognizer = [[UIRotationGestureRecognizer alloc] initWithTarget:self action:@selector(handleRotation:)];
_pinchRecognizer = [[UIPinchGestureRecognizer alloc] initWithTarget:self action:@selector(handlePinch:)];
_tapRecognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleTap:)];
```

in event viewDidLoad in file HFImageEditorViewController.m

**Comment by heitorfr** [comment]
Hi. Version 1.1.3 initializes the gesture recognizers in viewDidLoad. Check if it solves your problem.  v1.1.3 uses arc, you may hay to update your project.

**Comment by kohdesmond** [comment]
Hi Heitorfr,

Thanks will give it a go. thanks :)
