### ISSUE TITLE
Get crop rect (from original image)

### ISSUE THREAD

**Issue by eladleb** [heitorfr/ios-image-editor#2]
Is it possible to add the crop rect (x,y,width,height) of the new cropped image relatively to the original one?

**Comment by heitorfr** [comment]
Hi eladleb, can you elaborate a bit. I didn't understand exactly what you're trying to do.

**Comment by eladleb** [comment]
Hi, sure,
Say I have a original 400x400 image.
I cropped it, and as a result I got a 100x150 uiimage in the completion block.

I would love to know what is the origin point of the 100x150 uiimage, relatively to the original 400x400 image.

If it was the top left, I would expect a 0,0,100,150 CGRect.
If it was somewhere in the middle, then a 67,90, 100,150 CGRect would make sense.
![Screen Shot 2013-01-17 at 10 23 34 AM](https://f.cloud.github.com/assets/1809338/74171/3a48065e-607f-11e2-92d6-b4eb38e81363.png)

**Comment by heitorfr** [comment]
You have a new property - cropBoundsInSourceImage - that gives you the bounds of the crop rectangle in the image coordinates. Just remember that image coordinates start at the bottom left. And if there was rotation applied, the rect will represent the bounding box of the rotated crop rect. Hope it helps.

**Comment by eladleb** [comment]
Wow looking great!! works seamlessly.
This helps me a lot, thank you very much for taking the time to implement this property.
