### ISSUE TITLE
Crop rectangle is always a square?

### ISSUE THREAD

**Issue by dmauer** [heitorfr/ios-image-editor#24]
Hello, hopefully I'm just doing something wrong here, but despite setting the cropSize property, I'm always getting a square crop area.  Here's my code:

```
    HFImageEditorViewController *imageEditor = [[HFImageEditorViewController alloc] initWithNibName:@"ImageCropperView" bundle:nil];

    imageEditor.cropSize = CGSizeMake(312.0, 416.0);
    imageEditor.sourceImage = myImage;
    imageEditor.doneCallback = ^(UIImage *editedImage, BOOL canceled){
        if (canceled) {
            //do nothing
        } else {
            [self.myImageView setImage:editedImage];
        }
        [self.navigationController popViewControllerAnimated:NO];
    };
    [self.navigationController pushViewController:imageEditor animated:NO];
```

My "ImageCropperView" xib contains a toolbar at the bottom with the "done" and "cancel" buttons, and the frameView (of type HFImageEditorFrameView) fills the rest of the view.

...It doesn't seem that the value of imageEditor.cropSize has any effect whatsoever on the actual size of the crop rectangle.  Otherwise, everything works swimmingly.

Any help would be immensely appreciated!  Thanks.

**Comment by heitorfr** [comment]
Hi. HFImageEditorViewController is expecting cropSize or cropRect to be set only after its view and the frameView outlet have been set. If you subclass HFImageEditorViewController you can do it in viewDidLoad, as your not subclassing, Immediately after your call to 'pushViewController:animated:' should do the trick. Tell me if this solves your problem.
Thanks for pointing this outs, it's not well explained  on the documentation.

**Comment by dmauer** [comment]
Aha! Yes, that does it.  Thanks!
