### ISSUE TITLE
Please add new .podspec file to CocoaPods / Specs.

### ISSUE THREAD

**Issue by yoonchulkoh** [heitorfr/ios-image-editor#26]
I found 1.1.3 version of ios-image-editor.podspec file.
https://github.com/CocoaPods/Specs/blob/master/ios-image-editor/1.1.3/ios-image-editor.podspec

But could not find the 1.1.4 version file.
Please add new .podspec file.

Best regards.

**Comment by tfsjohan** [comment]
I agree!

**Comment by heitorfr** [comment]
finally done! future updates will be faster
