### ISSUE TITLE
implement in a basicViewController

### ISSUE THREAD

**Issue by viasisco** [heitorfr/ios-image-editor#3]
I've tried to implement your part of code which launches DemoImageEditor from a basic view controller instead of starting if from the AppDelegate and I have an issue in MY code : "[DemoImageEditor setCropRect:]: unrecognized selector sent to instance" because is not HFImageFrameView which launches setCropRest but the own view. And I don't understand why. Basicaly I have a simple view with a button.  I push the button to start UIImagePickerController in a (void) displayImagePickerWithSource where the *picker is instantieted with *library and *imageEditor which will be pushed to the DemoImageEditor.

**Comment by heitorfr** [comment]
I don't know if I'm understanding exactly. Do you mean 'setCropSize' ? (not 'setCropRect').

**Comment by viasisco** [comment]
SetCropSize works fine and is called by HFImageEditorViewController but setCropRect not, because it's not called by HFImageFrameView but by DemoImageEditor. I've just try to adapt the piece of code you've written in the appDelegate, application didFinishLaunchingWithOptions in a (ibaction)buttonPressed function.

**Comment by viasisco** [comment]
I gonna do a fork with a DemoImageEditor2 for example to launch the viewController with a button.

**Comment by heitorfr** [comment]
Ok, maybe I can help you if I see some code. Tell me when you've updated your fork.

**Comment by viasisco** [comment]
I did it in my fork  and it works ... fine. So I gonna try to reimplement it in my application.  Thanks for your work.

**Comment by viasisco** [comment]
I've found the reason why I'd an issue :  Compiler was on LLVM GCC2 instead of Apple LLVM compiler.  Can help others.
