### ISSUE TITLE
Broken in Xcode 6.1 & iOS8 SDK - Simulator

### ISSUE THREAD

**Issue by hackzilla** [heitorfr/ios-image-editor#36]
Dec  1 11:49:13 Daniels-MacBook-Pro.local ImageEditor[72522] <Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 32 bits/pixel; 3-component color space; kCGImageAlphaLast; 4096 bytes/row.

Dec  1 11:49:13 Daniels-MacBook-Pro.local ImageEditor[72522] <Error>: CGContextSetInterpolationQuality: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

Dec  1 11:49:13 Daniels-MacBook-Pro.local ImageEditor[72522] <Error>: CGContextTranslateCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

Dec  1 11:49:13 Daniels-MacBook-Pro.local ImageEditor[72522] <Error>: CGContextConcatCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

Dec  1 11:49:13 Daniels-MacBook-Pro.local ImageEditor[72522] <Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

Dec  1 11:49:13 Daniels-MacBook-Pro.local ImageEditor[72522] <Error>: CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by jostster** [comment]
I assume this library is dead

**Comment by betzerra** [comment]
Ditto
