### ISSUE TITLE
Blank space colour

### ISSUE THREAD

**Issue by ddaddy** [heitorfr/ios-image-editor#7]
Hi, this is great, thank you.
I'm just wondering, when I resize an image smaller than the crop area, or move it outside the crop area, the blank space left behind appears white in the crop area, however the resulting image that is processed has black for the blank space.

Is there any way to sync these? I don't mind setting the crop view to show black or the result to use white, as long as they are the same?

Thanks

**Comment by heitorfr** [comment]
Hi. Look in the following method:

```
- (CGImageRef)newTransformedImage:(CGAffineTransform)transform
                     sourceImage:(CGImageRef)sourceImage
                    sourceSize:(CGSize)sourceSize
           sourceOrientation:(UIImageOrientation)sourceOrientation
                 outputWidth:(CGFloat)outputWidth
                    cropSize:(CGSize)cropSize
               imageViewSize:(CGSize)imageViewSize
```

The lines below paint the blank space, so you can change it to another color or make it configurable. 

```
    CGContextSetFillColorWithColor(context,  [[UIColor clearColor] CGColor]);
    CGContextFillRect(context, CGRectMake(0, 0, outputSize.width, outputSize.height));
```

All the best

**Comment by ddaddy** [comment]
Thank you, i'll look at that.
