### ISSUE TITLE
Rounded corners in the crop view

### ISSUE THREAD

**Issue by ddaddy** [heitorfr/ios-image-editor#9]
Would it be possible to make the crop square have rounded corners?
I already clip the image's corners, but would like it to be visible to the user where it will be clipped.

Any pointers?

Thanks

**Comment by heitorfr** [comment]
Hi. I assume at this time you've moved on with your life :) But, for reference, you should be able to do what you want using a mask before drawing the image on the newTransformedImage method: https://developer.apple.com/library/mac/documentation/graphicsimaging/conceptual/drawingwithquartz2d/dq_images/dq_images.html

All the best.
